"""add missing tables

Revision ID: 3c858d8435c3
Revises: bb9141ace2f9
Create Date: 2024-12-08 14:57:56.529678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c858d8435c3'
down_revision = 'bb9141ace2f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('system_prompt', sa.String(length=262144), nullable=True),
    sa.Column('user_prompt', sa.String(length=262144), nullable=True),
    sa.Column('text_to_speech_use', sa.String(length=100), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.String(length=100), nullable=True),
    sa.Column('visibility', sa.String(length=100), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tts', sa.String(length=64), nullable=True),
    sa.Column('avatar_id', sa.String(length=100), nullable=True),
    sa.Column('background_text', sa.String(length=262144), nullable=True),
    sa.Column('rebyte_api_project_id', sa.String(length=100), nullable=True),
    sa.Column('rebyte_api_agent_id', sa.String(length=100), nullable=True),
    sa.Column('rebyte_api_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('server_message_unicode', sa.Unicode(length=65535), nullable=True),
    sa.Column('feedback', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Unicode(length=65535), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('client_message', sa.String(), nullable=True),
    sa.Column('server_message', sa.String(), nullable=True),
    sa.Column('client_message_unicode', sa.Unicode(length=65535), nullable=True),
    sa.Column('server_message_unicode', sa.Unicode(length=65535), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('character_id', sa.String(length=100), nullable=True),
    sa.Column('tools', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('llm_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_table('memory',
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('source_session_id', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Unicode(length=65535), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_table('quivr_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('quivr_api_key', sa.String(), nullable=True),
    sa.Column('quivr_brain_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quivr_info')
    op.drop_table('memory')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
