"""update models

Revision ID: bb9141ace2f9
Revises: 0823a2109835
Create Date: 2024-12-08 14:41:00.225334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9141ace2f9'
down_revision = '0823a2109835'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
